Edit group function
hayato-shirasaka/chat-space pull request #13
Opened 2016-11-27 09:47 UTC by hayato-shirasaka

2016-11-27 10:08 UTC, hc0208 requested changes

2016-11-27 10:08 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +    group = Group.find(params[:id])
@group= Group.find(params[:id])が2回でてきているので、privateメソッドとして定義して、before_actionで呼び出すようにしましょう。

2016-11-28 02:07 UTC, hayato-shirasaka commented on app/controllers/groups_controller.rb
> +    group = Group.find(params[:id])
set_groupにて@group= Group.find(params[:id])を呼び出すようにしました

2016-11-28 02:58 UTC, DaikiInaba commented on app/controllers/groups_controller.rb
> +    group = Group.find(params[:id])
上記の変更pushしていただいておりますでしょうか？

2016-11-28 02:58 UTC, DaikiInaba commented on app/views/groups/edit.html.haml
> +        =f.label :グループ名, class:"chat-group-form__label", id:"chat_group_name"
`:`の後ろは半角スペース入れましょう。
また、式展開を使用しない場合はシングルクォーテーションを使用しましょう。

2016-11-28 02:58 UTC, DaikiInaba commented on db/migrate/20161126110612_create_groups_users.rb
> +      t.references :group,foreign_key: true
`,`の後ろの半角スペース抜けていますね。

2016-11-28 02:58 UTC, DaikiInaba commented on app/views/groups/edit.html.haml
>            %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
一つだけinputタグというのは統一性に欠けるので、ここもhelperメソッドを使用しましょう！

2016-11-28 03:02 UTC, hayato-shirasaka commented on app/controllers/groups_controller.rb
> +    group = Group.find(params[:id])
pushを忘れていました。以後気をつけます。

2016-11-28 03:48 UTC, hayato-shirasaka commented on app/views/groups/edit.html.haml
> +        =f.label :グループ名, class:"chat-group-form__label", id:"chat_group_name"
修正しました。

2016-11-28 03:48 UTC, hayato-shirasaka commented on app/views/groups/edit.html.haml
>            %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
変更しました！

2016-11-28 03:49 UTC, hayato-shirasaka commented on db/migrate/20161126110612_create_groups_users.rb
> +      t.references :group,foreign_key: true
修正しました！

2016-11-28 06:17 UTC, hand12 reviewed
いくつかコメントしました！
すぐ直せると思うのでご確認ください！

2016-11-28 06:17 UTC, hand12 commented on app/controllers/groups_controller.rb
> +      render action: :edit
失敗した時もフラッシュメッセージは出るようにしましょう！

2016-11-28 06:17 UTC, hand12 commented on app/controllers/groups_users_controller.rb
> +end
使っていなければ削除しましょう！

2016-11-28 06:17 UTC, hand12 commented on app/views/groups/edit.html.haml
> +        =f.text_field :name, placeholder:"グループ名を入力してください", class: 'chat-group-form__input',id:'chat_group_name'
ここも,の後に半角スペースでね。
コードは読みやすさを意識すべきなので、,の後の半角スケースは癖をつけるようにしましょう！

2016-11-28 06:17 UTC, hand12 commented on app/views/groups/edit.html.haml
> +        =f.label :チャットメンバーを追加, class: 'chat-group-form__label',id: "chat_group_チャットメンバーを追加"
ここもですね！

2016-11-28 06:17 UTC, hand12 commented on app/views/groups/edit.html.haml
> +          = text_field_tag '', '', placeholder: "追加したいユーザー名を入力してください", id: 'user-search-field', class: 'chat-group-form__input'
他がform_forのヘルパーメソッドを使っているので、ここもf.text_fieldを使いましょう！

2016-11-28 06:50 UTC, hayato-shirasaka commented on app/controllers/groups_users_controller.rb
> +end
使用していないので削除しました。

2016-11-28 06:59 UTC, hayato-shirasaka commented on app/views/groups/edit.html.haml
> +        =f.label :チャットメンバーを追加, class: 'chat-group-form__label',id: "chat_group_チャットメンバーを追加"
修正しました！

2016-11-28 07:00 UTC, hayato-shirasaka commented on app/views/groups/edit.html.haml
> +        =f.text_field :name, placeholder:"グループ名を入力してください", class: 'chat-group-form__input',id:'chat_group_name'
意識しているようでできていないので、すぐに癖付けます！
修正しました！

2016-11-28 07:05 UTC, hayato-shirasaka commented on app/views/groups/edit.html.haml
> +          = text_field_tag '', '', placeholder: "追加したいユーザー名を入力してください", id: 'user-search-field', class: 'chat-group-form__input'
t.text_fieldに変更しました！

2016-11-28 07:12 UTC, hayato-shirasaka commented on app/views/groups/edit.html.haml
> +          = text_field_tag '', '', placeholder: "追加したいユーザー名を入力してください", id: 'user-search-field', class: 'chat-group-form__input'
変更しました。

2016-11-28 07:29 UTC, hayato-shirasaka commented on app/controllers/groups_controller.rb
> +      render action: :edit
修正しました！
alert: "チャットグループが更新されませんでした"では表示がされず引っ掛けでした！
リクエストとみなされるかみなされないかの違いでflashは使い分ける必要があるのですね

![2016-11-28 16 24 32](https://cloud.githubusercontent.com/assets/23450945/20659585/c65f001e-b587-11e6-828c-5b5e4bcafac0.png)

2016-11-28 08:17 UTC, hand12 reviewed
プルリク出す際にエラーが起きているのであれば、プルリク名にWIPをつけて、出す際も一言つけてくれると見る側も対応しやすいので次回からはそれでお願いいたします！

2016-11-28 08:17 UTC, hand12 commented on app/views/groups/new.html.haml
> +            = f.hidden_field : 'group[user_id]', value: ''
キーを指定する時はシンボルで指定するようにしましょう！

2016-11-28 09:07 UTC, hayato-shirasaka commented on app/views/groups/new.html.haml
> +            = f.hidden_field : 'group[user_id]', value: ''
修正いたしました。

2016-11-28 12:10 UTC, merged